---
# Deploying multiple containers
apiVersion: v1
kind: Pod
metadata:
  name: multi
#  namespace: roboshop
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  - name: almalinux
    image: almalinux  
    command: ["sleep","10"]