apiVersion: v1
kind: Pod
metadata:
  name: probe
spec:
  containers:
  - image: nginx
    name: nginx
    livenneesProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 3 # First it'll give 3 seconds 
      periodSeconds: 5 # Every 5 seconds it'll performm health checks of conatiner. If some thing goes then it'll restart! 