---
# In projects we ma've Hundred of variables
apiVersion: v1
kind: Pod
metadata:
  name: env
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      value: kubernetes
    - name: trainer
      value: selfpaced   