---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    server: nginx # Configuring labels, we can configure any no. of labels!
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
---
# Service Pod Definition:
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    server: nginx
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port
