
---
# imagePullPolicy
# We're asking to download the image from Docker Hub everytime.
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx  
    imagePullPolicy: Always
    ports:
    - containerPort: 80